name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31.0'
    - name: Preparation on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libasound2-dev jq
    - name: Preparation on Mac
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install jq
    - name: Get crate version on *nix platforms
      id: get_version_unix
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
        echo "crate_version=$VERSION" >> $GITHUB_OUTPUT
    - name: Get crate version on Windows
      id: get_version_windows
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        $meta = cargo metadata --no-deps --format-version 1 --manifest-path "$env:GITHUB_WORKSPACE\Cargo.toml" | ConvertFrom-Json
        $version = $meta.packages | Where-Object { $_.manifest_path -like "*\Cargo.toml" } | Select-Object -First 1 -ExpandProperty version
        Add-Content -Path $env:GITHUB_OUTPUT -Value "crate_version=$version"
    - name: Build
      run: |
        cargo build --verbose
        cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose -- --no-capture --test-threads=1
    - name: Upload artifacts on Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: spc2midi-tsuu_${{ steps.get_version_windows.outputs.crate_version }}_${{ matrix.os }}
        path: |
          target/release/spc2midi-tsuu.exe
        if-no-files-found: error
    - name: Upload artifacts on *nix platforms
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: spc2midi-tsuu_${{ steps.get_version_unix.outputs.crate_version }}_${{ matrix.os }}
        path: |
          target/release/spc2midi-tsuu
        if-no-files-found: error

